# Generated by Django 4.2.13 on 2024-10-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0003_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
