# Generated by Django 4.2.13 on 2024-11-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
